export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST'
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS'
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL'

export const JOB_EXPANDED_REQUEST = 'JOB_EXPANDED_REQUEST'
export const JOB_EXPANDED_SUCCESS = 'JOB_EXPANDED_SUCCESS'
export const JOB_EXPANDED_FAIL = 'JOB_EXPANDED_FAIL'