# Generated by Django 4.0.4 on 2022-04-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
